# src/Parser.py
# THIS CODE WILL HANDLE THE PARSER OBJECT. THIS OBJECT WILL TAKE A DICT OF REGEXES
# AND WILL EXTRACT THE STUFF FROM TEXT USING THE REGEX INTO A DICT WHERE THE KEYS WILL
# LINE UP BETWEEN THE REGEX AND THE OUTPUT

