name: Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      GEN_AI_STUDIO_API_KEY: fake-gen-ai-token
      HF_TOKEN: fake-hf-token
      GITHUB_TOKEN: fake-github-token
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requirements
        run: ./run install

      - name: Run flake8 (Linting)
        run: flake8 src/* tests/*

      - name: Run mypy (Type Annotation)
        run: mypy src/

      - name: Run unit tests
        run: pytest --cov=src tests/*.py
